### ISSUE TITLE
Query: Training Result Interpretation, and Performance Indicators

### ISSUE THREAD

**Issue by SmashSoar** [v-iashin/SpecVQGAN#37]
Hello,
I have some confusion about the saved results during the training process , and I was wondering if you could kindly help clarify this for me? I really appreciate your help!

(1) Why are there two spectrograms saved in the input and reconstructed image, while there is only one corresponding audio? For example, in the image ‘inputs_gs-039871_e-007_b-004500.png’, there are two spectrograms stacked vertically, but there is only one corresponding audio. However, it seems strange that TensorBoard can display both ‘input0’ and ‘input1’ for this.
![image](https://github.com/v-iashin/SpecVQGAN/assets/152368732/3fbac118-8aef-46f0-9042-586d024a24be)
**_tensorboard screenshot_**
![image](https://github.com/v-iashin/SpecVQGAN/assets/152368732/9e4b074e-44d4-4f17-bd09-e69ae69826ad)
(2) How should we interpret the generated images of att_det, att_half, att_nopix, conditioning, samples_det, samples_half, and samples_nopix during the training process? How do they indicate the quality of the training results?
![image](https://github.com/v-iashin/SpecVQGAN/assets/152368732/e1a6e18d-cbdd-40be-9067-a8fb063b6651)
Thank you so much for your patience and assistance. I apologize if my questions seem basic. Your help is greatly appreciated and I hope I’m not causing too much trouble.

**Comment by v-iashin** [comment]
Hi,

No worries, I am happy to help.

1) Could it be that your batch size is >=2 and it displays the spectrogram for the first two elements? It is governed by `ImageLogger` class and the `max_images` argument.

2) `att_det, att_half, att_nopix` depict attention across all previous tokens for each position. Pick a row (y-coordinate) in one of the two images, and it will show you the transformer's attention for all previous positions (all x-coordinates until x=y). The fact that only the lower half and right half are highlighted means that most of the attention is on the generated sequence, rather than on the conditioning sequence.

What is the difference between `_det/half/nopix`? `half` gives the first half of the output from the ground truth and the model should sample the rest. `nopix` (no pixels in condition) samples all spectrogram tokens but without any condition provided (aka 'no feats'). `det` (deterministic sampling) does not _sample_ from the distribution (distribution across the vocabulary of codes) but simply picks the code that has the max probability.
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/specvqgan/models/cond_transformer.py#L238-L263

`conditioning` and `rec_conditioning` should be the same. One could use another VQGAN for conditioning, ie. depth VQGAN as in the VQGAN paper, or cluster ids if clustering is used instead. In this case, `rec_conditioning` would give you a sense of how well that VQGAN performs, but here I don't use another VQGAN for conditioning but use features.
See, no transforms is applied to `c`:
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/specvqgan/models/cond_transformer.py#L281
and 
https://github.com/v-iashin/SpecVQGAN/blob/8ab6981535ab70fad3531688e0f630f1ce3b834f/specvqgan/modules/misc/raw_feats.py#L17-L18

`samples_*` are the generated examples for the cases as explained for `att*`

**Comment by SmashSoar** [comment]
@v-iashin 
Hello,
Thank you for your detailed explanation and guidance! I have resolved the first issue. Due to my batch size = 2 and max images = 4, the model might have generated two audio outputs, but the later one overwrote the earlier one, resulting in only one audio remaining. I will change the max images to 1.
Your answer to the second question was very informative, and I now have a general understanding of the principles involved. I will thoroughly study the corresponding code files.
Thank you again for your help!
